config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :projects
    resources :goals
    resources :indicators
    resources :project_users

    root to: "users#index"
  end

  devise_for :users

  devise_scope :user do
      authenticated :user do
          resources :projects, only: [:index, :show]
          resources :snapshots, only: [:create]
          post 'snapshots/share', to: 'snapshots#share'
          patch 'entries/:id', to: 'entries#update'
          get 'entries/:id', to: 'entries#show'
          get 'effects', to: 'effects#create'
          get 'projects/:id/:status(/indicator/:indicator_id)', to: 'projects#show', as: 'filtered_project', defaults: { status: 'shared' }
          root "projects#index"
      end

      unauthenticated do
        get 'share/:id(/indicator/:indicator_id)', to: 'snapshots#show', as: 'report'
        get 'share/:public_id/entry/:id', to: 'entries#show_in_report', as: 'report_entry'
        root to: "devise/sessions#new"
      end
  end


  namespace :auth do
      mount_devise_token_auth_for 'User', skip: [:omniauth_callbacks], controllers: { sessions: 'overrides/sessions', passwords: 'overrides/passwords' }
  end

  api_version(:module => "V20170220", :header => {:name => "Accept", :value => "v20170220"}) do
    resources :entries, only: [:create, :index, :show, :update]
    resources :projects, only: [:create, :index]
  end

  root to: 'devise/sessions#new'
end

app/views/shared/_count_indicator_progress.html.slim
.indicator.indicator-count
    .font-weight-bold.indicator-title
        = indicator.title
    .text-muted
        = indicator.description
    .indicator-progressbar.my-3
        .progress
            .progress-bar { aria-valuemin="#{indicator.baseline}"
                            aria-valuemax="#{indicator.target}"
                            aria-valuenow="#{indicator.current_value(point_in_time)}"
                            role="progressbar"
                            style="width: #{indicator.target_percent_achieved(point_in_time) * 100}%;"
                          }
        - if indicator.current_value(point_in_time) > indicator.baseline
            span.some-progress-text
                = "#{indicator.current_value(point_in_time)} out of #{indicator.target}"
            span.text-muted
                =" (starting point #{indicator.baseline})"
        - else
            span.no-progress-text.text-muted
                = "#{indicator.current_value(point_in_time)} out of #{indicator.target}"

app/views/shared/_effect.html.slim
= fields_for "#{scope}", effect do |effect_fields|
    tr
        td.effect-input
            - if effect.indicator.is_count?
                = effect_fields.number_field(:cumulative_value_one, { class: 'form-control' } )

            - elsif effect.indicator.is_percent?
                .form-row
                    .col
                        = effect_fields.number_field(:cumulative_value_one, { class: 'form-control', width: '50%' } )
                    .col
                        = effect_fields.number_field(:cumulative_value_two, { class: 'form-control', width: '50%' } )

            - elsif effect.indicator.is_traffic_light?
                = effect_fields.collection_select(:cumulative_value_one, Indicator.traffic_light_definitions, :last, :first)

            - else
                | Unknown indicator

        td.effect-indicator-title
            = effect_fields.hidden_field 'indicator_id', { value: effect.indicator.id }
            = effect.indicator.title

        td.effect-deactivate
            .onoffswitch
                = effect_fields.check_box(:is_active?, { id: "entry#{effect.entry.id}-#{scope}-switch", class: "onoffswitch-checkbox" } )
                label{ class="onoffswitch-label" for="entry#{effect.entry.id}-#{scope}-switch" }

app/views/shared/_entry_metadata.html.slim
.entry-metadata.clearfix
    .avatar
        = render partial: "shared/user_avatar", locals: { user: entry.user }
    .other-metadata
        .author-name
            = entry.user.name
        .relative-date.text-muted
            = "#{time_ago_in_words(entry.created_on_auto)} ago"

app/views/shared/_goal_progress.html.slim
.goal.py-3
    .goal-metadata
        h4
            = goal.title
        .text-muted
            = goal.description
    - if goal.indicators.count > 0
        - goal.indicators.each do |i|
            = render partial: "shared/indicator_progress", locals: { indicator: i, current_indicator: current_indicator, point_in_time: point_in_time, base_path_sym: base_path_sym, base_path_id: base_path_id }

app/views/shared/_indicator_progress.html.slim
- if !current_indicator.nil? and current_indicator.id.eql?(indicator.id)
    .active.arrow_box
        - if indicator.is_count?
            = render partial: "shared/count_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_percent?
            = render partial: "shared/percent_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_traffic_light?
            = render partial: "shared/traffic_light_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - else
            .font-italic
                | Unkown Indicator (#{indicator.title})
- elsif !base_path_sym.nil? and !base_path_id.nil?
    = link_to send(base_path_sym, { id: base_path_id, indicator_id: indicator.id })
        - if indicator.is_count?
            = render partial: "shared/count_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_percent?
            = render partial: "shared/percent_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_traffic_light?
            = render partial: "shared/traffic_light_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - else
            .font-italic
                | Unkown Indicator (#{indicator.title})
- else
    .plain-indicator
        - if indicator.is_count?
            = render partial: "shared/count_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_percent?
            = render partial: "shared/percent_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - elsif indicator.is_traffic_light?
            = render partial: "shared/traffic_light_indicator_progress", locals: { indicator: indicator, point_in_time: point_in_time }
        - else
            .font-italic
                | Unkown Indicator (#{indicator.title})

app/views/shared/_pending_entry.html.slim
.collapse.show{ id = "entry#{entry.id}-card" }
    .card.my-4
        - if entry.attachments.count == 0
            img class='card-img-top' src='http://via.placeholder.com/500x250'
        - else
            .carousel.slide{ data-ride="carousel" id="entry-#{entry.id}-carousel" }
                - if entry.attachments.count > 1
                    ol.carousel-indicators
                        - entry.attachments.each_with_index do |a, i|
                            - if i.eql?(0)
                                li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" class="active" }
                            - else
                                li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" }
                .carousel-inner.entry-image-carousel
                    - entry.attachments.each_with_index do |a, i|
                        - if !a.download_url.nil?
                            - if i.eql?(0)
                                .carousel-item.active
                                    = image_tag a.download_url, class: "entry-image"
                            - else
                                .carousel-item
                                    = image_tag a.download_url, class: "entry-image"
                        - else
                            - if i.eql?(0)
                                .carousel-item.active
                                    img src='http://via.placeholder.com/500x250' class="d-block w-100"
                            - else
                                .carousel-item
                                    img src='http://via.placeholder.com/500x250' class="d-block w-100"
                - if entry.attachments.count > 1
                    a.carousel-control-prev{ href="#entry-#{entry.id}-carousel" role="button" data-slide="prev" }
                        span{ class="carousel-control-prev-icon" }
                    a.carousel-control-next{ href="#entry-#{entry.id}-carousel" role="button" data-slide="next" }
                        span{ class="carousel-control-next-icon" }



        .card-body
            = render partial: "shared/entry_metadata", locals: { entry: entry }

            h4.card-title.font-weight-bold.my-3
                - if entry.title.blank?
                    .font-italic
                        | (no title)
                - else
                    = entry.title

            .card-subtitle.mt-2
                - if entry.description.blank?
                    .font-italic
                        | (no description)
                - else
                    = entry.description


        .card-body.effects.mt-2
            = form_for entry, { html: { class: "entry#{entry.id}-form" }, remote: true } do |entry_fields|
                - effects = entry.effects.select { |ef| ef.status.eql?('active') }
                - if effects.count > 0
                    .entry-effects-title
                        | Does this change the value of the affected indicators?

                    table.indicators
                        - effects.each do |ef|
                            = entry_fields.fields_for :effects, ef, index: ef.id do |effect_fields|
                                tr
                                    td.effect-input
                                        - if ef.indicator.is_count?
                                            = effect_fields.number_field(:cumulative_value_one, { class: 'form-control' } )

                                        - elsif ef.indicator.is_percent?
                                            .form-row
                                                .col
                                                    = effect_fields.number_field(:cumulative_value_one, { class: 'form-control', width: '50%' } )
                                                .col
                                                    = effect_fields.number_field(:cumulative_value_two, { class: 'form-control', width: '50%' } )

                                        - elsif ef.indicator.is_traffic_light?
                                            = effect_fields.collection_select(:cumulative_value_one, Indicator.traffic_light_definitions, :last, :first)

                                        - else
                                            | Unknown indicator

                                    td.effect-indicator-title
                                        = effect_fields.hidden_field 'indicator_id', { value: ef.indicator.id }
                                        = ef.indicator.title

                                    td.effect-deactivate
                                        .onoffswitch
                                            = effect_fields.check_box(:is_active?, { id: "entry#{entry.id}-effect#{ef.id}-switch", class: "onoffswitch-checkbox" } )
                                            label{ class="onoffswitch-label" for="entry#{entry.id}-effect#{ef.id}-switch" }


                - else
                    | No indicators
                    br
                table.indicators.new-effects-holder{ id="entry#{entry.id}-new-effects" }
                = hidden_field_tag "entry[status]", "publish"
                = hidden_field_tag "entry[div_id]", "#entry#{entry.id}-card"
                .collapse{ id="entry#{entry.id}-deleteWarning" }
                    .alert.alert-danger.my-2
                        | Deleting a post is a permanent action and can not be undone. Are you sure?
                        .delete-buttons
                            button.btn.btn-danger.m-2.delete-post-button{ data-target=".entry#{entry.id}-form" type="button" }
                                | Yes, go ahead and delete
                            button.btn.btn-secondary.m-2{ data-toggle="collapse" data-target="#entry#{entry.id}-deleteWarning" type="button" }
                                | Keep for now
                .entry-actions.mt-3.clearfix
                    = select_tag "add-indicator",
                        options_for_select( ( entry.project.indicators - entry.effects.collect { |ef| ef.indicator if ef.is_active? } ).collect{ |i| [i.title, i.id] }),
                        {   class: "custom-select additional-indicator-select my-2",
                            prompt: "Add an indicator",
                            data: { entryid: "#{entry.id}", target: "#entry#{entry.id}-new-effects", neweffectvalue: -1 } }
                    = entry_fields.submit "Share!", { class: "btn btn-primary m-2" }
                    button.btn.btn-secondary.m-2{ data-toggle="collapse" data-target="#entry#{entry.id}-deleteWarning" type="button" }
                        | Delete post

app/views/shared/_percent_indicator_progress.html.slim
.indicator.indicator-percent
    .font-weight-bold.indicator-title
        = indicator.title
    .text-muted
        = indicator.description
    .indicator-progressbar.my-3
        .progress
            .progress-bar { aria-valuemin="#{indicator.baseline}"
                            aria-valuemax="#{indicator.target}"
                            aria-valuenow="#{indicator.current_value(point_in_time)}"
                            role="progressbar"
                            style="width: #{indicator.target_percent_achieved(point_in_time) * 100}%;"
                          }
        - if indicator.current_value(point_in_time) > indicator.baseline
            span.some-progress-text
                = "#{(indicator.current_value(point_in_time) * 100).to_i}% out of #{indicator.target}%"
            span.text-muted
                =" (starting point #{indicator.baseline}%)"
        - else
            span.no-progress-text.text-muted
                = "#{number_to_percentage(indicator.current_value(point_in_time) * 100, precision: 2)} out of #{indicator.target}%"

app/views/shared/_public_published_entry.html.slim
.card.my-4
    - if entry.attachments.count == 0
        img class='card-img-top' src='http://via.placeholder.com/500x250'
    - else
        .carousel.slide{ data-ride="carousel" id="entry-#{entry.id}-carousel" }
            - if entry.attachments.count > 1
                ol.carousel-indicators
                    - entry.attachments.each_with_index do |a, i|
                        - if i.eql?(0)
                            li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" class="active" }
                        - else
                            li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" }
            .carousel-inner.entry-image-carousel
                - entry.attachments.each_with_index do |a, i|
                    - if !a.download_url.nil?
                        - if i.eql?(0)
                            .carousel-item.active
                                = image_tag a.download_url, class: "entry-image"
                        - else
                            .carousel-item
                                = image_tag a.download_url, class: "entry-image"
                    - else
                        - if i.eql?(0)
                            .carousel-item.active
                                img src='http://via.placeholder.com/500x250' class="d-block w-100"
                        - else
                            .carousel-item
                                img src='http://via.placeholder.com/500x250' class="d-block w-100"
            - if entry.attachments.count > 1
                a.carousel-control-prev{ href="#entry-#{entry.id}-carousel" role="button" data-slide="prev" }
                    span{ class="carousel-control-prev-icon" }
                a.carousel-control-next{ href="#entry-#{entry.id}-carousel" role="button" data-slide="next" }
                    span{ class="carousel-control-next-icon" }



    .card-body
        = render partial: "shared/entry_metadata", locals: { entry: entry }

        h4.card-title.font-weight-bold.my-3
            - if entry.title.blank?
                .font-italic
                    | (no title)
            - else
                = entry.title

        .card-subtitle.my-2
            - if entry.description.blank?
                .font-italic
                    | (no description)
            - else
                = entry.description

        .card-more-link.mt-2
            = link_to "See more", report_entry_path(@snapshot.public_id, entry)

app/views/shared/_published_entry.html.slim
.card.my-4
    - if entry.attachments.count == 0
        img class='card-img-top' src='http://via.placeholder.com/500x250'
    - else
        .carousel.slide{ data-ride="carousel" id="entry-#{entry.id}-carousel" }
            - if entry.attachments.count > 1
                ol.carousel-indicators
                    - entry.attachments.each_with_index do |a, i|
                        - if i.eql?(0)
                            li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" class="active" }
                        - else
                            li{ data-target="#entry-#{entry.id}-carousel" data-slide="#{i}" }
            .carousel-inner.entry-image-carousel
                - entry.attachments.each_with_index do |a, i|
                    - if !a.download_url.nil?
                        - if i.eql?(0)
                            .carousel-item.active
                                = image_tag a.download_url, class: "entry-image"
                        - else
                            .carousel-item
                                = image_tag a.download_url, class: "entry-image"
                    - else
                        - if i.eql?(0)
                            .carousel-item.active
                                img src='http://via.placeholder.com/500x250' class="d-block w-100"
                        - else
                            .carousel-item
                                img src='http://via.placeholder.com/500x250' class="d-block w-100"
            - if entry.attachments.count > 1
                a.carousel-control-prev{ href="#entry-#{entry.id}-carousel" role="button" data-slide="prev" }
                    span{ class="carousel-control-prev-icon" }
                a.carousel-control-next{ href="#entry-#{entry.id}-carousel" role="button" data-slide="next" }
                    span{ class="carousel-control-next-icon" }



    .card-body
        = render partial: "shared/entry_metadata", locals: { entry: entry }

        h4.card-title.font-weight-bold.my-3
            - if entry.title.blank?
                .font-italic
                    | (no title)
            - else
                = entry.title

        .card-subtitle.my-2
            - if entry.description.blank?
                .font-italic
                    | (no description)
            - else
                = entry.description

        .card-more-link.mt-2
            = link_to "See more", entry_path(entry)

app/views/shared/_traffic_light_indicator_progress.html.slim
div{ class="indicator indicator-traffic-light #{indicator.current_value(point_in_time).to_s}" }
    .font-weight-bold.indicator-title
        = indicator.title
    .text-muted
        = indicator.description
    .status.my-3
        - if indicator.current_value(point_in_time).eql?(:red)
            | Off track
        - elsif indicator.current_value(point_in_time).eql?(:yellow)
            | Needs work
        - elsif indicator.current_value(point_in_time).eql?(:green)
            | On track
        - else
            | Unknown

app/views/shared/_user_avatar.html.slim
- if user.avatar and !user.avatar.blank?
    = image_tag user.avatar.url, alt: user.name, title: user.name, class: "rounded-circle user-avatar"
- else
    span.user-avatar.empty-user-avatar{ title=user.name }