config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :projects
    resources :goals
    resources :indicators
    resources :project_users

    root to: "users#index"
  end

  devise_for :users

  devise_scope :user do
      authenticated :user do
          resources :projects, only: [:index, :show]
          resources :snapshots, only: [:create]
          post 'snapshots/share', to: 'snapshots#share'
          patch 'entries/:id', to: 'entries#update'
          get 'entries/:id', to: 'entries#show'
          get 'effects', to: 'effects#create'
          get 'projects/:id/:status(/indicator/:indicator_id)', to: 'projects#show', as: 'filtered_project', defaults: { status: 'shared' }
          root "projects#index"
      end

      unauthenticated do
        get 'share/:id(/indicator/:indicator_id)', to: 'snapshots#show', as: 'report'
        get 'share/:public_id/entry/:id', to: 'entries#show_in_report', as: 'report_entry'
        root to: "devise/sessions#new"
      end
  end


  namespace :auth do
      mount_devise_token_auth_for 'User', skip: [:omniauth_callbacks], controllers: { sessions: 'overrides/sessions', passwords: 'overrides/passwords' }
  end

  api_version(:module => "V20170220", :header => {:name => "Accept", :value => "v20170220"}) do
    resources :entries, only: [:create, :index, :show, :update]
    resources :projects, only: [:create, :index]
  end

  root to: 'devise/sessions#new'
end

app/models/project.rb
class Project < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :description

  has_attached_file :hero, styles: { thumb: '200x200>', medium: '400x400>' }, default_style: :thumb
  validates_attachment_content_type :hero, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_file_name    :hero, :matches => [/png\Z/, /jpe?g\Z/, /gif\Z/]

  has_many :project_users
  has_many :users, through: :project_users
  has_many :goals
  has_many :indicators, through: :goals
  has_many :effects, through: :indicators
  has_many :entries, -> { distinct }, through: :effects

  def add_goals_and_indicators goals_data
    goals_data.each do |goal_data|
      goal = Goal.find_or_initialize_by(title: goal_data['title'])
      unless goal.project
        goal.assign_attributes(goal_data.select { |key| Goal.attribute_names.index(key) })
        goals << goal
      end
      goal.add_indicators goal_data['indicators']
    end
  end

  def add_users users_data
    users_data.each do |user_data|
      user = User.find_or_initialize_by(email: user_data['email'])
      user.assign_attributes(user_data.select { |key| User.attribute_names.index(key) })
      user.password = (0...12).map { (65 + rand(26)).chr }.join
      unless ProjectUser.find_by(project: self, user: user)
        users << user
        project_users.last.roles = user_data['project_roles']
      end
    end
  end

  def managers
    self.project_users.includes(:user).
      select { |project_user| project_user.roles.include? 'manager' }.
      map    { |project_user| project_user.user }
  end

  def roles user
    self.project_users.where(user_id: user.id).first.roles
  end

  def send_queued_entries_email
    return if self.entries.submitted.count == 0
    ProjectMailer.queued_entries_email(self).deliver
  end

  def self.send_all_queued_entries_emails
    Project.all.each { |p| p.send_queued_entries_email }
  end

  def self.create_from_json_file file
    project_data = JSON.parse(file.read)
    project = Project.find_or_initialize_by(title: project_data['title'])
    project.description = project_data['description']
    project.add_users project_data['users']
    project.add_goals_and_indicators project_data['goals']
    project.save!
    project
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      @projects = Project.all.includes(:entries)
    else
      @projects = current_user.projects.includes(:entries)
    end

    respond_to do |format|
        format.html
    end
  end

  def show
    @project = Project.find(project_params[:id])

    status          = project_params[:status]
    @viewing_pending = (!status.blank? and status.downcase.eql?('pending'))

    @team = @project.project_users.select { |pu| !pu.is_impactive_admin? }

    candidate_entries = @project.entries.published
    candidate_entries = @project.entries.submitted if @viewing_pending

    indicator = indicator_filter(@project)
    @indicator = nil
    if indicator
        candidate_entries = candidate_entries
                                    .joins(:effects)
                                    .where(effects: { indicator_id: indicator.id, status: 'active' })
        @indicator = indicator
    end

    if @viewing_pending
        @entries = candidate_entries.page(params[:page]).per(10).order(created_at: :asc)
    else
        @entries = candidate_entries.page(params[:page]).per(10).order(created_at: :desc)
    end

    @goals      = @project.goals
    @indicators = @project.indicators
    @point_in_time = Time.now

    respond_to do |format|
        format.html
    end
  end

  private

  def indicator_filter(project)
    i_id = project_params[:indicator_id]
    indicator = project.indicators.where(id: i_id).first
    return indicator
  end

  def project_params
    params.permit(:id, :indicator_id, :page, :status)
  end
end

app/controllers/v20170220/projects_controller.rb
class V20170220::ProjectsController < V20170220::BaseController
	before_action :authenticate_user!

  def create
    if current_user.admin?
      begin
        project = Project.create_from_json_file params['file']
        render json: project, each_serializer: ConsoleProjectSerializer
      rescue => error
        render json: { errors: [error] }, status: 400
      end
    else
      render json: { errors: ['Unauthorized request'] }, status: 401
    end
  end

  def index
    if params['console']
      projects = current_user.admin? ? Project.all.includes(:entries) : current_user.projects.includes(:entries)
      render json: projects, each_serializer: ConsoleProjectSerializer
    else
      render json: current_user.projects.select { |project| current_user.field_agent? project }
    end
  end
end

app/views/projects/index.html.slim
- @projects.each_slice(3) do |r|
    .my-4.card-deck
        - r.each do |p|
            a class='card' href='#{project_path(p)}'
                - if p.hero and !p.hero.blank?
                    img class='card-img-top' src='#{p.hero.url}'
                - else
                    = image_tag 'default_project_hero.png', class: 'card-img-top'
                .card-body.m-3
                    h4.card-title.font-weight-bold
                        = p.title
                    .card-subtitle.mt-1
                        = truncate(p.description, length: 80)

        - (3-r.count).times do
            .card.border-0

app/views/projects/show.html.slim
.row
    .col-md-7
        .row
            .col-md-12
                h2.title.my-3
                    = button_to "Share", snapshots_path, { class: 'btn share-button btn-warning', remote: true, params: { project_id: @project.id, modal_target: '#share-modal', url_target: '#share-report-url', form_target: '.snapshot-public-id-hidden-input' } }
                    = @project.title

                p.subtitle.my-3
                    = @project.description

                ul.nav.nav-tabs
                    - pending_link_class = published_link_class = "nav-link"
                    - pending_link_class   += ' active' if @viewing_pending
                    - published_link_class += ' active' unless @viewing_pending


                    li.nav-item
                    li{ class="#{ @viewing_pending ? 'nav-item' : 'nav-item active' }" }
                        - if @indicator.nil?
                            a{ class="#{published_link_class}" href="#{ filtered_project_path(status: 'shared') }" } Shared
                        - else
                            a{ class="#{published_link_class}" href="#{ filtered_project_path(status: 'shared', indicator_id: @indicator.id) }" } Shared

                    li.nav-item
                    li{ class="#{ @viewing_pending ? 'nav-item active' : 'nav-item' }" }
                        - if @indicator.nil?
                            a{ class="#{pending_link_class}" href="#{ filtered_project_path(status: 'pending')  }" } Pending
                        - else
                            a{ class="#{pending_link_class}" href="#{ filtered_project_path(status: 'pending', indicator_id: @indicator.id)  }" } Pending

                .tab-content
                    .tab-pane.active
                        - unless @indicator.nil?
                            .filtered-project-advisory.my-3
                                h6
                                    | Showing #{@entries.count} posts affecting
                                    span.filtered-indicator-title
                                       = " #{@indicator.title}"
                                .unfiltered-project-link
                                    = link_to "Show all activity instead", @project
                        - if @viewing_pending
                            #pending
                                - @entries.each do |entry|
                                    = render partial: "shared/pending_entry", locals: { entry: entry }

                                = paginate @entries

                        - else
                            #published
                                - @entries.each do |entry|
                                    = render partial: "shared/published_entry", locals: { entry: entry }

                                = paginate @entries


    .col-md-4
        .team.mb-5
            h5 Team
            - if @team.count > 0
                - @team.each do |u|
                    = render partial: "shared/user_avatar", locals: { user: u.user }

        - if @goals.count > 0
            .indicators.my-5
                h5 Indicators
                - @goals.each do |g|
                    = render partial: "shared/goal_progress", locals: { goal: g, current_indicator: @indicator, point_in_time: @point_in_time, base_path_sym: :filtered_project_path, base_path_id: @project.id }

.modal#share-modal
    .modal-dialog.modal-lg
        .modal-content
            .modal-header
                h4.modal-title
                    | Share project
                .close{ data-dismiss="modal" }
                    span
                        | &times;

            .modal-body

                .row.share-url-desc.mt-4
                    .col-md-12
                        | Copy this private url to share
                .row.share-url-block.mb-2
                    .col-md-8
                        .form-control#share-report-url
                            = link_to project_path, "Project"
                    .col-md-4
                        button.btn.btn-primary.btn-block.clipboard-btn{ data-clipboard-target="#share-report-url" }
                            | Copy

                .row.share-divider
                    .col-md-12
                        hr

                .row.share-email-desc.mt-2
                    .col-md-12
                        | Email the url to share
                = form_tag '/snapshots/share', { remote: true, class: 'row share-email-block mb-4' }
                    .col-md-8
                        = text_field_tag "email_addresses", nil, { placeholder: 'Enter email addresses separated by commas', class: 'form-control' }
                        = hidden_field_tag "public_id", nil, { class: 'snapshot-public-id-hidden-input' }
                    .col-md-4
                        = submit_tag "Email", class: 'btn btn-primary btn-block'

                .row.share-email-success-block.collapse#email-share-success-message
                    .col-md-12
                        .alert.alert-success.my-2
                            | Got it! We shared your report with&nbsp;
                            span#email-addresses-success-message
                                = current_user.email