config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users
    resources :projects
    resources :goals
    resources :indicators
    resources :project_users

    root to: "users#index"
  end

  devise_for :users

  devise_scope :user do
      authenticated :user do
          resources :projects, only: [:index, :show]
          resources :snapshots, only: [:create]
          post 'snapshots/share', to: 'snapshots#share'
          patch 'entries/:id', to: 'entries#update'
          get 'entries/:id', to: 'entries#show'
          get 'effects', to: 'effects#create'
          get 'projects/:id/:status(/indicator/:indicator_id)', to: 'projects#show', as: 'filtered_project', defaults: { status: 'shared' }
          root "projects#index"
      end

      unauthenticated do
        get 'share/:id(/indicator/:indicator_id)', to: 'snapshots#show', as: 'report'
        get 'share/:public_id/entry/:id', to: 'entries#show_in_report', as: 'report_entry'
        root to: "devise/sessions#new"
      end
  end


  namespace :auth do
      mount_devise_token_auth_for 'User', skip: [:omniauth_callbacks], controllers: { sessions: 'overrides/sessions', passwords: 'overrides/passwords' }
  end

  api_version(:module => "V20170220", :header => {:name => "Accept", :value => "v20170220"}) do
    resources :entries, only: [:create, :index, :show, :update]
    resources :projects, only: [:create, :index]
  end

  root to: 'devise/sessions#new'
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  belongs_to :project
  belongs_to :user

  def self.create_with_ids(user_id, project_id)
    candidate_id = Snapshot.generate_new_public_id
    until (Snapshot.where(public_id: candidate_id).count == 0) do
        candidate_id = Snapshot.generate_new_public_id
    end
    snapshot = Snapshot.new(user_id: user_id, project_id: project_id, public_id: candidate_id)
    snapshot
  end

  private

  def self.generate_new_public_id
    # Remove I, L, O, U since people misread them occasionally
    charset = %w{ A B C D E F G H J K M N P Q R S T V W X Y Z}
    (0...6).map{ charset.to_a[rand(charset.size)] }.join
  end

end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  layout "report", except: [:create, :share]
  before_action :authenticate_user!, except: [:show]

  def create
    @snapshot = Snapshot.create_with_ids(current_user, snapshot_params[:project_id])
    @snapshot.save!

    @modal_target = snapshot_params[:modal_target]
    @form_target  = snapshot_params[:form_target]
    @url_target   = snapshot_params[:url_target]
  end

  def share
    @snapshot = Snapshot.where(public_id: snapshot_params[:public_id]).first
    @emails = snapshot_params[:email_addresses]

    UserMailer.report_shared_email(current_user, @snapshot, @emails).deliver
  end

  def show
    @snapshot = Snapshot.where(public_id: snapshot_params[:id]).first

    @project = @snapshot.project
    @team    = @project.project_users.select { |pu| !pu.is_impactive_admin? }
    @goals   = @project.goals

    @point_in_time = @snapshot.created_at
    candidate_entries = @project.entries.published.created_before(@point_in_time)

    indicator = indicator_filter(@project)
    @indicator = nil
    if indicator
        candidate_entries = candidate_entries
                                    .joins(:effects)
                                    .where(effects: { indicator_id: indicator.id, status: 'active' })
        @indicator = indicator
    end

    @entries = candidate_entries.page(params[:page]).per(10).order(created_at: :desc)

    respond_to do |format|
        format.html
    end
  end

  private

  def indicator_filter(project)
    i_id = snapshot_params[:indicator_id]
    indicator = project.indicators.where(id: i_id).first
    return indicator
  end


  def snapshot_params
    params.permit([:id, :public_id, :project_id, :modal_target, :form_target, :url_target, :indicator_id, :page, :email_addresses])
  end
end

app/views/snapshots/create.js.erb
$('<%= j @url_target %>').html(" <%= j report_url(id: @snapshot.public_id, only_path: false) %> ");
$('<%= j @form_target %>').val("<%= @snapshot.public_id %>");
$('<%= j @modal_target %>').modal('show');

app/views/snapshots/share.js.erb
$('#email-addresses-success-message').html(" <%= j @emails %> ");
$('#email-share-success-message').collapse('show');

app/views/snapshots/show.html.slim
- content_for :report_date, @point_in_time.to_date.to_formatted_s(:long)

.row
    .col-md-7
        .row
            .col-md-12
                h2.title.my-3
                    = @project.title

                p.subtitle.my-3
                    = @project.description

                    - unless @indicator.nil?
                        .filtered-project-advisory.my-3
                            h6
                                | Showing #{@entries.count} posts affecting
                                span.filtered-indicator-title
                                   = " #{@indicator.title}"
                            .unfiltered-project-link
                                = link_to "Show all activity instead", report_path(@snapshot.public_id)

                    #published
                        - @entries.each do |entry|
                            = render partial: "shared/public_published_entry", locals: { snapshot: @snapshot, entry: entry }

                        = paginate @entries


    .col-md-4
        .team.mb-5
            h5 Team
            - if @team.count > 0
                - @team.each do |u|
                    = render partial: "shared/user_avatar", locals: { user: u.user }

        - if @goals.count > 0
            .indicators.my-5
                h5 Indicators
                - @goals.each do |g|
                    = render partial: "shared/goal_progress", locals: { goal: g, current_indicator: @indicator, point_in_time: @point_in_time, base_path_sym: :report_path, base_path_id: @snapshot.public_id }